#!/bin/bash

rm -f jsload-unsigned.zip

if [ -f "$(which google-chrome-stable)" ]; then
	  
	if [ ! -d "/etc/opt/chrome/native-messaging-hosts/" ]; then
		sudo mkdir -p /etc/opt/chrome/native-messaging-hosts/
	fi

	sudo cp native-app/db_connector-chrome.json /etc/opt/chrome/native-messaging-hosts/db_connector.json
	sudo cp native-app/db_connector.py /etc/opt/chrome/native-messaging-hosts/db_connector.py
fi

if [ -f "$(which chromium-browser)" ]; then
	  
	if [ ! -d "/etc/chromium/native-messaging-hosts/" ]; then
		sudo mkdir -p /etc/chromium/native-messaging-hosts/
	fi

	sudo cp native-app/db_connector-chromium.json /etc/chromium/native-messaging-hosts/db_connector.json
	sudo cp native-app/db_connector.py /etc/chromium/native-messaging-hosts/db_connector.py
fi

zip -r jsload-unsigned.zip *
